# Generated by Django 5.2.5 on 2025-09-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="user_id",
            new_name="user",
        ),
    ]
