# Generated by Django 5.2.5 on 2025-09-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_rename_user_id_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
