# Generated by Django 5.2.5 on 2025-09-03 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_day",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
            preserve_default=False,
        ),
    ]
