blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: Bug Report
    description: Report a bug or unexpected behavior
    labels: ["bug"]
    file: bug_report.md

  - name: Feature Request
    description: Propose a new feature or idea
    labels: ["enhancement"]
    file: feature.md
