name: Add labels from 'feature_type'
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Extract labels from body issue
        id: extract
        run: |
          echo "Body:"
          echo "${{ github.event.issue.body }}"
          echo "----"
          matched_labels=()
          while read -r line; do
            case "$line" in
              "- [x] Frontend") matched_labels+=("Frontend") ;;
              "- [x] Backend") matched_labels+=("Backend") ;;
              "- [x] Mobile") matched_labels+=("Mobile") ;;
            esac
          done <<< "${{ github.event.issue.body }}"
          # Écrire les étiquettes dans un fichier temporaire pour éviter les problèmes avec $GITHUB_OUTPUT
          printf '%s\n' "${matched_labels[@]}" > labels.txt
          echo "labels_file=labels.txt" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Debug labels
        run: |
          echo "Étiquettes extraites :"
          cat labels.txt
          echo "Étiquettes ligne par ligne :"
          while IFS= read -r label; do
            echo "Étiquette : '$label'"
          done < labels.txt
        shell: bash
      - name: Add labels to the issue
        if: steps.extract.outputs.labels_file != ''
        run: |
          while IFS= read -r label; do
            if [ -n "$label" ]; then
              echo "Ajout de l'étiquette : '$label'"
              gh issue edit ${{ github.event.issue.number }} --add-label "$label" --repo ${{ github.repository }}
            fi
          done < labels.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash