name: api-ci
on:
  push:
    branches: 
      - "backend"
  pull_request:
    branches: 
      - "backend"

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore SubManager.sln

    - name: Build
      run: dotnet build SubManager.sln --no-restore

    - name: Run tests
      run: dotnet test SubManager.sln --no-build --verbosity normal